//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int id_profile { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_lang { get; set; }
        public Nullable<int> socre { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
    
        public virtual lang lang { get; set; }
        public virtual usert usert { get; set; }
    }
}
